Stop optinal service before purging a package

diff --git a/ytl-linux-purge-deb/ytl-linux-purge-deb b/ytl-linux-purge-deb/ytl-linux-purge-deb
--- a/ytl-linux-purge-deb/ytl-linux-purge-deb
+++ b/ytl-linux-purge-deb/ytl-linux-purge-deb
@@ -19,9 +19,31 @@ purge_package () {
     apt-get --yes purge $package
 }
 
+stop_service () {
+    service=$1
+
+    logger --tag=$TAG "Stopping service $service"
+    systemctl stop $service
+    RESULT=$?
+    if [ $RESULT -gt 0 ]; then
+        logger --tag=$TAG "Stopping service $service failed with exit code $RESULT"
+    fi
+
+    logger --tag=$TAG "Disabling service $service"
+    systemctl disable $service
+    RESULT=$?
+    if [ $RESULT -gt 0 ]; then
+        logger --tag=$TAG "Disabling service $service failed with exit code $RESULT"
+    fi
+}
+
 while IFS="" read -r line || [ -n "$line" ]
 do
-    package_name=`echo $line | sed 's|\s||g'`
+    line_without_whitespaces=`echo $line | sed 's|\s||g'`
+
+    package_name=`echo $line_without_whitespaces | awk -F':' '{print $1}'`
+    service_name=`echo $line_without_whitespaces | awk -F':' '{print $2}'`
+
     if [ -z "$package_name" ]; then
         continue
     fi
@@ -32,6 +54,10 @@ do
 
     is_installed $package_name
     if [ $? -gt 0 ]; then
+        if [ ! -z "$service_name" ]; then
+            stop_service $service_name
+        fi
+
         purge_package $package_name
     fi
 done < /etc/ytl-linux-purge-deb.conf
