Use shared constants from wrapper script instead, scaffold functionality

diff --git a/packages/ytl-linux-digabi2-examnet/justfile b/packages/ytl-linux-digabi2-examnet/justfile
--- a/packages/ytl-linux-digabi2-examnet/justfile
+++ b/packages/ytl-linux-digabi2-examnet/justfile
@@ -1,13 +1,18 @@
 mod setup 'lib/setup.just'
 
-# Shared constants
-# TODO: Naksu uses exit codes 6, 20, 24, 25 so these should not be changed
-# Exit code 1 is reserved for generic unexpected exits
-export EXIT_CODE_MUST_BE_ROOT := 2
-export EXIT_CODE_NO_SUCH_NETWORK_DEVICE := 3
-export EXIT_CODE_INVALID_SERVER_NUMBER := 4
-export EXIT_CODE_INVALID_SERVER_NAME := 5
-export EXIT_CODE_SAME_DEVICE_FOR_WAN_AND_LAN := 6
-export EXIT_CODE_NO_IP_ON_NETWORK_DEVICE := 7
+[private]
+default:
+    @just --list --unsorted
 
-configure: setup::apply
+configure net-device-wan net-device-lan server-number server-name: assert-user-is-root
+  just setup apply {{net-device-wan}} {{net-device-lan}} {{server-number}} {{server-name}}
+
+[private]
+assert-user-is-root:
+  #!/usr/bin/env bash
+  set -euo pipefail
+
+  if [[ ${TEST_MODE:-} != "test" && $EUID -ne 0 ]]; then
+    echo "Error: This script must be run as root"
+    exit $EXIT_CODE_MUST_BE_ROOT
+  fi
