Add automatic happy path tests for examnet
- examnet script supports flag --not-root which allows running the script as non-root user
- call external programs as they are found in path
- allow overriding paths
- add automatic tests that call the examnet script

diff --git a/packages/ytl-linux-digabi2-examnet/ytl-linux-digabi2-examnet b/packages/ytl-linux-digabi2-examnet/ytl-linux-digabi2-examnet
--- a/packages/ytl-linux-digabi2-examnet/ytl-linux-digabi2-examnet
+++ b/packages/ytl-linux-digabi2-examnet/ytl-linux-digabi2-examnet
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
 
+# These domains and their subdomains are allowed from LAN to WAN for Windows Defender cloud verification.
+# Keep this list minimal.
+readonly INTERNET_ALLOWLIST_DOMAINS=(
+    "endpoint.security.microsoft.com"
+    "smartscreen-prod.microsoft.com"
+    "smartscreen.microsoft.com"
+)
+
 # Exit codes
 readonly EXIT_CODE_MUST_BE_ROOT=1                     # The script must be executed by root or sudo
 readonly EXIT_CODE_NETWORK_DEVICE_NAME_MISSING_WAN=2  # Network device name (internet) is missing
@@ -41,44 +49,29 @@ readonly FRIENDLY_NAME_SEARCH_DOMAIN="internal"
 readonly DISCOVERY_PORT=26464
 readonly BOUNCER_PORT=80
 
-readonly PATH_TEMPLATES=/etc/ytl-linux-digabi2-examnet/templates
-readonly PATH_RESOLVED=/etc/systemd/resolved.conf.d
+readonly PATH_TEMPLATES=${PATH_TEMPLATES:-/etc/ytl-linux-digabi2-examnet/templates}
+readonly PATH_RESOLVED=${PATH_RESOLVED:-/etc/systemd/resolved.conf.d}
 readonly PATH_RESOLVED_CONF=$PATH_RESOLVED/ytl-linux.conf
 readonly PATH_RESOLVED_CONF_TEMPLATE=$PATH_TEMPLATES/resolved.conf.template
-readonly PATH_DNSMASQ=/etc/dnsmasq.d
+readonly PATH_DNSMASQ=${PATH_DNSMASQ:-/etc/dnsmasq.d}
 readonly PATH_DNSMASQ_CONF=$PATH_DNSMASQ/ytl-linux.conf
 readonly PATH_DNSMASQ_CONF_TEMPLATE=$PATH_TEMPLATES/dnsmasq.conf.template
 readonly PATH_DNSMASQ_STATIC_DNS_CONF=$PATH_DNSMASQ/ytl-linux-static-dns-records.conf
 readonly PATH_DNSMASQ_KTP_ALIASES_CONF=$PATH_DNSMASQ/ytl-linux-ktp-aliases.conf
-readonly PATH_DOCKER=/etc/docker
+readonly PATH_DNSMASQ_IPSET_ALLOWLIST_CONF=$PATH_DNSMASQ/ytl-linux-internet-allowlist-ipset.conf
+readonly PATH_DNSMASQ_SERVER_ALLOWLIST_CONF=$PATH_DNSMASQ/ytl-linux-internet-allowlist-server.conf
+readonly PATH_DOCKER=${PATH_DOCKER:-/etc/docker}
 readonly PATH_DOCKER_DAEMON_CONF=$PATH_DOCKER/daemon.json
 readonly PATH_NAKSU2_WORKDIR="${NAKSU2_WORKDIR:-/home/school/.local/share/digabi/naksu2}"
 readonly PATH_NAKSU2_CERTS_DIR="$PATH_NAKSU2_WORKDIR/certs"
 readonly PATH_NAKSU2_CERT="$PATH_NAKSU2_CERTS_DIR/cert.pem"
 readonly PATH_NAKSU2_DOMAIN="$PATH_NAKSU2_CERTS_DIR/domain.txt"
-readonly PATH_EXAMNET_CONFIG=/etc/ytl-linux-digabi2-examnet/config/
+readonly PATH_EXAMNET_CONFIG="${PATH_EXAMNET_CONFIG:-/etc/ytl-linux-digabi2-examnet/config/}"
 readonly PATH_SERVER_FRIENDLY_NAME_CONF=$PATH_EXAMNET_CONFIG/server-friendly-name
 readonly PATH_NET_DEVICE_LAN_CONF=$PATH_EXAMNET_CONFIG/net-device-lan
 readonly PATH_NET_DEVICE_WAN_CONF=$PATH_EXAMNET_CONFIG/net-device-wan
 readonly PATH_SERVER_OWN_IP=$PATH_EXAMNET_CONFIG/server-own-ip
 readonly PATH_DISCOVERY_DB=$PATH_EXAMNET_CONFIG/discovery.db
-
-readonly BIN_ECHO=/usr/bin/echo
-readonly BIN_GREP=/usr/bin/grep
-readonly BIN_TR=/usr/bin/tr
-readonly BIN_CUT=/usr/bin/cut
-readonly BIN_IP=/usr/sbin/ip
-readonly BIN_MKDIR=/usr/bin/mkdir
-readonly BIN_SYSTEMCTL=/usr/bin/systemctl
-readonly BIN_NMCLI=/usr/bin/nmcli
-readonly BIN_NM_ONLINE=/usr/bin/nm-online
-readonly BIN_SED=/usr/bin/sed
-readonly BIN_XARGS=/usr/bin/xargs
-readonly BIN_OPENSSL=/usr/bin/openssl
-readonly BIN_DIGABI2_EXAMNET_BOUNCER=/usr/local/libexec/ytl-linux-digabi2-examnet/bouncer
-readonly BIN_DIGABI2_EXAMNET_DISCOVERY=/usr/local/libexec/ytl-linux-digabi2-examnet/discovery
-readonly BIN_STAT=/usr/bin/stat
-readonly BIN_CHOWN=/usr/bin/chown
 
 readonly CONST_MIN_SERVER_NUMBER=1
 readonly CONST_MAX_SERVER_NUMBER=24
@@ -87,7 +80,7 @@ readonly CONST_SUBNETS_PER_SERVER=10
 function get_dir_owner() {
     _DIR=$1
     if [ -d "$_DIR" ]; then
-        $BIN_STAT -c '%U:%G' "$_DIR"
+        stat -c '%U:%G' "$_DIR"
     fi
 }
 
@@ -95,9 +88,9 @@ readonly NAKSU2_WORKDIR_OWNER=$(get_dir_owner "$PATH_NAKSU2_WORKDIR")
 
 function debug_path() {
     if [ -z "$DEBUG" ]; then
-        $BIN_ECHO "/dev/null"
+        echo "/dev/null"
     else
-        $BIN_ECHO "$DEBUG"
+        echo "$DEBUG"
     fi
 }
 
@@ -106,29 +99,29 @@ readonly PATH_DEBUG
 
 function debug() {
     _DEBUG_MESSAGE=$1
-    $BIN_ECHO "$SCRIPT_PATH DEBUG: $_DEBUG_MESSAGE" >>"$PATH_DEBUG"
+    echo "$SCRIPT_PATH DEBUG: $_DEBUG_MESSAGE" #>>"$PATH_DEBUG"
 }
 
 function print_error() {
     _ERROR_MESSAGE=$1
     debug "ERROR: $_ERROR_MESSAGE"
-    $BIN_ECHO "$SCRIPT_PATH error: $_ERROR_MESSAGE" >&2
+    echo "$SCRIPT_PATH error: $_ERROR_MESSAGE" >&2
 }
 
 function print_info() {
     _INFO_MESSAGE=$1
     debug "INFO: $_INFO_MESSAGE"
-    $BIN_ECHO "$SCRIPT_PATH info: $_INFO_MESSAGE"
+    echo "$SCRIPT_PATH info: $_INFO_MESSAGE"
 }
 
 function print_usage() {
-    $BIN_ECHO "usage: $SCRIPT_PATH wan-network-device local-network-device server-number [custom-server-name] [--use-static-local-dns]" >&2
-    $BIN_ECHO "       $SCRIPT_PATH --daemon" >&2
-    $BIN_ECHO "       $SCRIPT_PATH --restart-daemon" >&2
-    $BIN_ECHO "       $SCRIPT_PATH --discover" >&2
-    $BIN_ECHO "       $SCRIPT_PATH --remove" >&2
-    $BIN_ECHO "" >&2
-    $BIN_ECHO "example: $SCRIPT_PATH eth0 eth1 1" >&2
+    echo "usage: $SCRIPT_PATH wan-network-device local-network-device server-number [custom-server-name] [--use-static-local-dns] [--not-root]" >&2
+    echo "       $SCRIPT_PATH --daemon" >&2
+    echo "       $SCRIPT_PATH --restart-daemon" >&2
+    echo "       $SCRIPT_PATH --discover" >&2
+    echo "       $SCRIPT_PATH --remove" >&2
+    echo "" >&2
+    echo "example: $SCRIPT_PATH eth0 eth1 1" >&2
 }
 
 function exit_script() {
@@ -166,14 +159,14 @@ function network_enumerate_devices () {
 
 function network_device_exists() {
     _DEVICE=$1
-    $BIN_IP link show "$_DEVICE" &> /dev/null && $BIN_ECHO "1"
+    ip link show "$_DEVICE" &> /dev/null && echo "1"
 }
 
 function get_ipv4_address() {
     _DEVICE=$1
-    _IP=$($BIN_IP -oneline -4 addr show scope global "$_DEVICE" | $BIN_TR -s ' ' | $BIN_TR '/' ' ' | $BIN_CUT -f 4 -d ' ')
+    _IP=$(ip -oneline -4 addr show scope global "$_DEVICE" | tr -s ' ' | tr '/' ' ' | cut -f 4 -d ' ')
     if [[ ! "$_IP" =~ "does not exist" ]]; then
-        $BIN_ECHO "$_IP"
+        echo "$_IP"
     fi
 }
 
@@ -217,7 +210,7 @@ function check_network_device_names() {
 function server_number_is_valid() {
     _SERVER_NUMBER=$1
     if [[ "$_SERVER_NUMBER" =~ ^[0-9]+$ ]] && [ "$_SERVER_NUMBER" -ge $CONST_MIN_SERVER_NUMBER ] && [ "$_SERVER_NUMBER" -le $CONST_MAX_SERVER_NUMBER ]; then
-        $BIN_ECHO "1"
+        echo "1"
     fi
 }
 
@@ -241,9 +234,9 @@ function get_lan_ip_prefix() {
     _IP_WAN=$1
 
     if [[ "$_IP_WAN" =~ ^192\.168\. ]]; then
-        $BIN_ECHO "10.0."
+        echo "10.0."
     else
-        $BIN_ECHO "192.168."
+        echo "192.168."
     fi
 }
 
@@ -255,21 +248,21 @@ function write_file() {
     _FILE_PATH=$(dirname "$_FILE_FILENAME")
     if [ ! -d "$_FILE_PATH" ]; then
         debug "Path $_FILE_PATH is missing, creating"
-        $BIN_MKDIR -p "$_FILE_PATH"
+        mkdir -p "$_FILE_PATH"
         exit_if_error $? $EXIT_CODE_BAD_FILE_PATH "Failed to create directory $_FILE_PATH"
         if [ -n "$_FILE_OWNER" ]; then
-            $BIN_CHOWN "$_FILE_OWNER" "$_FILE_PATH"
+            chown "$_FILE_OWNER" "$_FILE_PATH"
         fi
     else
         debug "Path $_FILE_PATH exists"
     fi
 
     debug "$_FILE_FILENAME: $_FILE_CONTENT"
-    $BIN_ECHO -e "$_FILE_CONTENT" >"$_FILE_FILENAME"
+    echo -e "$_FILE_CONTENT" >"$_FILE_FILENAME"
     exit_if_error $? $EXIT_CODE_CANNOT_WRITE "Failed to write to $_FILE_FILENAME"
 
     if [ -n "$_FILE_OWNER" ]; then
-        $BIN_CHOWN "$_FILE_OWNER" "$_FILE_FILENAME"
+        chown "$_FILE_OWNER" "$_FILE_FILENAME"
     fi
 }
 
@@ -279,12 +272,12 @@ function configure_networkmanager() {
     _IP_AND_NETMASK=$3
 
     debug "Deleting existing NetworkManager connection '$_CONNECTION_NAME'"
-    $BIN_NMCLI connection delete "$_CONNECTION_NAME" >>"$PATH_DEBUG" 2>&1
+    nmcli connection delete "$_CONNECTION_NAME" >>"$PATH_DEBUG" 2>&1
     # We are not checking the exit code as this command fails if the connection does not exist
     # This is quite normal if the script has been executed before
 
     debug "Adding NetworkManager connection '$_CONNECTION_NAME'"
-    $BIN_NMCLI connection add \
+    nmcli connection add \
         type ethernet \
         ifname "$_INTERFACE_NAME" \
         con-name "$_CONNECTION_NAME" \
@@ -294,11 +287,11 @@ function configure_networkmanager() {
     exit_if_error $? $EXIT_CODE_CANNOT_RESTART_LAN_DEVICE "NetworkManager CLI: connection add $_CONNECTION_NAME failed"
 
     debug "Disabling IPv6 in connection '$_CONNECTION_NAME'"
-    $BIN_NMCLI connection modify "$_CONNECTION_NAME" ipv6.method "disabled" >>"$PATH_DEBUG" 2>&1
+    nmcli connection modify "$_CONNECTION_NAME" ipv6.method "disabled" >>"$PATH_DEBUG" 2>&1
     exit_if_error $? $EXIT_CODE_CANNOT_RESTART_LAN_DEVICE "NetworkManager CLI: IPv6 disable failed"
 
     debug "Starting connection '$_CONNECTION_NAME'"
-    $BIN_NMCLI connection up "$_CONNECTION_NAME" >>"$PATH_DEBUG" 2>&1
+    nmcli connection up "$_CONNECTION_NAME" >>"$PATH_DEBUG" 2>&1
     exit_if_error $? $EXIT_CODE_CANNOT_RESTART_LAN_DEVICE "Failed to start NetworkManager connection '$_CONNECTION_NAME'"
 }
 
@@ -355,31 +348,31 @@ function remove_all_settings() {
     remove_dnsmasq_settings
     remove_school_host_entries
 
-    $BIN_NMCLI -f UUID,NAME connection show | $BIN_GREP -P -v "^UUID" | $BIN_TR -s ' ' | while read -r line ; do
-        connection_uuid=$(echo "$line" | $BIN_CUT -d ' ' -f 1)
-        connection_name=$(echo "$line" | $BIN_CUT -d ' ' -f 2)
+    nmcli -f UUID,NAME connection show | grep -P -v "^UUID" | tr -s ' ' | while read -r line ; do
+        connection_uuid=$(echo "$line" | cut -d ' ' -f 1)
+        connection_name=$(echo "$line" | cut -d ' ' -f 2)
         if [[ "$connection_name" =~ ^yo- ]]; then
             debug "Removing connection '$connection_name', uuid: $connection_uuid"
-            $BIN_NMCLI connection delete "$connection_uuid"
+            nmcli connection delete "$connection_uuid"
             exit_if_error $? $EXIT_CODE_CANNOT_REMOVE_CONNECTION "Failed to remove connection '$connection_name'"
         fi
     done
 }
 
 function restart_systemd_resolved() {
-    $BIN_SYSTEMCTL restart systemd-resolved
+    systemctl restart systemd-resolved
     exit_if_error $? $EXIT_CODE_CANNOT_RESTART_RESOLVED "Failed to restart systemd-resolved"
 }
 
 function restart_dnsmasq() {
     if [[ "$(systemctl is-enabled dnsmasq.service)" == "enabled" ]]; then
-        $BIN_SYSTEMCTL restart dnsmasq.service >>"$PATH_DEBUG" 2>&1
+        systemctl restart dnsmasq.service >>"$PATH_DEBUG" 2>&1
         exit_if_error $? $EXIT_CODE_CANNOT_RESTART_DNSMASQ "Failed to restart dnsmasq.service"
     fi
 }
 
 function restart_networkmanager() {
-    $BIN_SYSTEMCTL restart NetworkManager.service >>"$PATH_DEBUG" 2>&1
+    systemctl restart NetworkManager.service >>"$PATH_DEBUG" 2>&1
     exit_if_error $? $EXIT_CODE_CANNOT_RESTART_NM "Failed to restart NetworkManager.service"
 }
 
@@ -390,24 +383,24 @@ function wait_for_network_online() {
         _TIMEOUT=30
     fi
 
-    $BIN_NM_ONLINE -s -q --timeout="$_TIMEOUT" >>"$PATH_DEBUG" 2>&1
+    nm-online -s -q --timeout="$_TIMEOUT" >>"$PATH_DEBUG" 2>&1
 
     exit_if_error $? $EXIT_CODE_NETWORK_NOT_ONLINE "Network did not become online within timeout"
 }
 
 function restart_examnet_daemon() {
     if [[ "$(systemctl is-enabled ytl-linux-digabi2-examnet.service)" == "enabled" ]]; then
-        $BIN_SYSTEMCTL restart ytl-linux-digabi2-examnet.service >>"$PATH_DEBUG" 2>&1
+        systemctl restart ytl-linux-digabi2-examnet.service >>"$PATH_DEBUG" 2>&1
         exit_if_error $? $EXIT_CODE_CANNOT_CHANGE_SERVICE_STATE "Failed to restart ytl-linux-digabi2-examnet.service"
     fi
 
     if [[ "$(systemctl is-enabled ytl-linux-digabi2-examnet-discovery.timer)" == "enabled" ]]; then
-        $BIN_SYSTEMCTL restart ytl-linux-digabi2-examnet-discovery.timer >>"$PATH_DEBUG" 2>&1
+        systemctl restart ytl-linux-digabi2-examnet-discovery.timer >>"$PATH_DEBUG" 2>&1
         exit_if_error $? $EXIT_CODE_CANNOT_CHANGE_SERVICE_STATE "Failed to restart ytl-linux-digabi2-examnet-discovery.timer"
     fi
 
     if [[ "$(systemctl is-enabled ytl-linux-digabi2-examnet-discovery.service)" == "enabled" ]]; then
-        $BIN_SYSTEMCTL restart ytl-linux-digabi2-examnet-discovery.service >>"$PATH_DEBUG" 2>&1
+        systemctl restart ytl-linux-digabi2-examnet-discovery.service >>"$PATH_DEBUG" 2>&1
         exit_if_error $? $EXIT_CODE_CANNOT_CHANGE_SERVICE_STATE "Failed to restart ytl-linux-digabi2-examnet-discovery.service"
     fi
 }
@@ -448,7 +441,7 @@ function disable_systemd_services() {
 }
 
 function restart_docker() {
-    $BIN_SYSTEMCTL restart docker
+    systemctl restart docker
     exit_if_error $? $EXIT_CODE_CANNOT_RESTART_DOCKER "Failed to restart docker"
 }
 
@@ -466,12 +459,12 @@ function configure_static_dns_records() {
     # Parse out SANs from certificate; only include server subdomains (e.g. ktp1.1000.koe.abitti.net), not the "root subdomain"
     # (e.g. 1000.koe.abitti.net) since we cannot reasonably ascribe DNS names to these
     DOMAINS="$(
-        $BIN_OPENSSL x509 -in "$PATH_NAKSU2_CERT" -text -noout |\
-        $BIN_GREP DNS: |\
-        $BIN_XARGS |\
-        $BIN_SED 's/DNS://g' |\
-        $BIN_SED 's/, /\n/g' |\
-        $BIN_GREP -E '(.+\..+){4}'
+        openssl x509 -in "$PATH_NAKSU2_CERT" -text -noout |\
+        grep DNS: |\
+        xargs |\
+        sed 's/DNS://g' |\
+        sed 's/, /\n/g' |\
+        grep -E '(.+\..+){4}'
     )"
 
     debug "Configuring static DNS records for the following domains:"
@@ -484,7 +477,7 @@ function configure_static_dns_records() {
     for DOMAIN in $DOMAINS; do
         debug "Generating DNS record for domain: $DOMAIN"
 
-        SERVER_NUMBER="$($BIN_ECHO "$DOMAIN" | $BIN_CUT -d '.' -f1 | $BIN_TR -dc '[:digit:]')"
+        SERVER_NUMBER="$(echo "$DOMAIN" | cut -d '.' -f1 | tr -dc '[:digit:]')"
 
         if [ "$SERVER_NUMBER" == "$_SERVER_NUMBER" ]; then
             THIS_SERVER_DOMAIN=$DOMAIN
@@ -502,7 +495,7 @@ function configure_static_dns_records() {
     fi
 
     debug "Generated DNS records: ${DNS_RECORDS[*]}"
-    write_file $PATH_DNSMASQ_STATIC_DNS_CONF "$(IFS=$'\n'; $BIN_ECHO "${DNS_RECORDS[*]}")"
+    write_file $PATH_DNSMASQ_STATIC_DNS_CONF "$(IFS=$'\n'; echo "${DNS_RECORDS[*]}")"
 
     debug "Generated /etc/hosts entries: ${ETC_HOSTS[*]}"
 
@@ -530,7 +523,7 @@ if [ -z "$PARAM_NET_DEVICE_WAN" ]; then
     exit_script $EXIT_CODE_NETWORK_DEVICE_NAME_MISSING_WAN
 fi
 
-if [ ! "$(current_user_is_root)" ]; then
+if [[ $* != *--not-root* && ! "$(current_user_is_root)" ]]; then
     print_error "You're not root"
     exit_script $EXIT_CODE_MUST_BE_ROOT
 fi
@@ -556,23 +549,23 @@ if [[ $* == *--daemon* ]]; then
     fi
 
     CONFIG=$(cat <<EOF
-    {
-        "config": {
-            "friendlyName": $(jq -Rc . "$PATH_SERVER_FRIENDLY_NAME_CONF"),
-            "canonicalHostname": $(jq -Rc . "$PATH_NAKSU2_DOMAIN"),
-            "ncsiHostnames": $(jq -Rc '.|split(",")|map(select(.!=""))' "$PATH_EXAMNET_CONFIG/ncsi-hostnames"),
-            "searchDomain": "$FRIENDLY_NAME_SEARCH_DOMAIN",
-            "serverOwnIp": $(jq -Rc . "$PATH_SERVER_OWN_IP"),
-            "ports": {"discovery": $DISCOVERY_PORT, "bouncer": $BOUNCER_PORT}
-        },
+    {\
+        "config": {\
+            "friendlyName": $(jq -Rc . "$PATH_SERVER_FRIENDLY_NAME_CONF"), \
+            "canonicalHostname": $(jq -Rc . "$PATH_NAKSU2_DOMAIN"), \
+            "ncsiHostnames": $(jq -Rc '.|split(",")|map(select(.!=""))' "$PATH_EXAMNET_CONFIG/ncsi-hostnames"), \
+            "searchDomain": "$FRIENDLY_NAME_SEARCH_DOMAIN", \
+            "serverOwnIp": $(jq -Rc . "$PATH_SERVER_OWN_IP"), \
+            "ports": {"discovery": $DISCOVERY_PORT, "bouncer": $BOUNCER_PORT} \
+        }, \
         "secrets": $(jq -nc '{cert:$cert, key:$key}' \
             --arg cert "$PATH_NAKSU2_CERTS_DIR/fullchain.pem" \
-            --arg key "$PATH_NAKSU2_CERTS_DIR/key.pem"
-        )
+            --arg key "$PATH_NAKSU2_CERTS_DIR/key.pem" \
+        ) \
     }
 EOF
     )
-    $BIN_DIGABI2_EXAMNET_BOUNCER "$CONFIG"
+    ytl-linux-digabi2-bouncer "$CONFIG"
 
     # We're not supposed to get here, so this would indicate the daemon process exited
     exit_script $EXIT_CODE_DAEMON_EXITED_UNEXPECTEDLY
@@ -604,7 +597,7 @@ if [[ $* == *--discover* ]]; then
 EOF
     )
 
-    $BIN_DIGABI2_EXAMNET_DISCOVERY "$CONFIG"
+    ytl-linux-digabi2-discovery "$CONFIG"
 
     exit_if_error $? $EXIT_CODE_CANNOT_RUN_ALIAS_DISCOVERY "Failed to run alias discovery"
     exit 0
